// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilieuFourthWPF;

namespace MilieuFourthWPF.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20210228163922_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Milieu.Models.Account.ClientSide.LoginCredentialsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLogout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jwt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasIndex("LastEntry");

                    b.ToTable("LoginCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
